"""Hand-assigned topic labels for every message, in timestamp order.

Unsupervised clustering (HDBSCAN, KMeans on MiniLM embeddings) produced
mushy clusters on these short chat messages, so topics were assigned by a
close reading of the full transcript (Claude, 2026-08-04). Each entry is
(author_name, topic) aligned to messages.parquet sorted by ts; the merge
script asserts the name column matches to catch any misalignment.
"""

TOPICS = {
    "greet": {"label": "Hellos", "color": "#a78bfa"},
    "hype": {"label": "Cheering & awe", "color": "#f472b6"},
    "emoji": {"label": "Pure emoji", "color": "#fbbf24"},
    "congrats": {"label": "Congratulations", "color": "#e879f9"},
    "lore": {"label": "Wasita lore", "color": "#60a5fa"},
    "meta": {"label": "The chat itself & AI jokes", "color": "#34d399"},
    "science": {"label": "The science", "color": "#f87171"},
    "tangent": {"label": "Krispy Kreme & Mohegan tangent", "color": "#fb923c"},
    "connection": {"label": "Feeling connected", "color": "#c084fc"},
    "thanks": {"label": "Thank-you slide feels", "color": "#5eead4"},
}

LABELS = [
    ("dae", "greet"),
    ("Robert H", "greet"),
    ("Yong", "hype"),
    ("Alicia", "greet"),
    ("Emma!", "hype"),
    ("Erik", "hype"),
    ("mimi", "greet"),
    ("yuna!", "hype"),
    ("Tommy", "hype"),
    ("kushin", "greet"),
    ("JasonH", "greet"),
    ("Helen", "hype"),
    ("Dominique", "hype"),
    ("Jphil", "hype"),
    ("Robby", "emoji"),
    ("James", "hype"),
    ("mimi", "hype"),
    ("Jae", "hype"),
    ("Maisy", "hype"),
    ("Katie!", "hype"),
    ("Hetvi", "hype"),
    ("Helen", "hype"),
    ("Robert H", "hype"),
    ("Alana", "hype"),
    ("Neilly", "hype"),
    ("Jphil", "lore"),
    ("Romy", "hype"),
    ("Pete", "emoji"),
    ("LT", "hype"),
    ("Dhaval", "hype"),
    ("Jan", "hype"),
    ("Alexis :)", "emoji"),
    ("Emily Finn", "hype"),
    ("JasonH", "emoji"),
    ("Alana", "hype"),
    ("Grace < 3", "emoji"),
    ("Yugantar", "emoji"),
    ("Tommy", "meta"),
    ("alexis ;)", "hype"),
    ("Chris Welker", "hype"),
    ("Jan", "emoji"),
    ("Emma!", "hype"),
    ("Chelsea Mills", "hype"),
    ("Paxton", "emoji"),
    ("Eshin", "meta"),
    ("Emma!", "meta"),
    ("Kay", "emoji"),
    ("Erin", "greet"),
    ("Guillaume", "lore"),
    ("Gabriel R.", "hype"),
    ("Tor", "hype"),
    ("Robert H", "science"),
    ("kushin", "meta"),
    ("Amitai", "emoji"),
    ("Romy", "connection"),
    ("alexis ;)", "meta"),
    ("Alana", "meta"),
    ("Nir", "emoji"),
    ("Cindy", "lore"),
    ("Jphil", "emoji"),
    ("Alana", "connection"),
    ("Ben", "emoji"),
    ("yuna!", "meta"),
    ("Thalia", "emoji"),
    ("Erin", "lore"),
    ("dae", "lore"),
    ("yuna!", "lore"),
    ("Katie!", "lore"),
    ("Robert H", "emoji"),
    ("Chelsea Mills", "lore"),
    ("Dominique", "lore"),
    ("Emily Finn", "meta"),
    ("Who dis", "meta"),
    ("Gabriel R.", "emoji"),
    ("Luke Chang", "meta"),
    ("Jphil", "meta"),
    ("Jacqueline Chang", "lore"),
    ("Jacqueline Chang", "lore"),
    ("Tor", "emoji"),
    ("Jphil", "meta"),
    ("Ben", "science"),
    ("sushpici0us", "hype"),
    ("kushin", "science"),
    ("Robert H", "science"),
    ("Matthew Gordon", "hype"),
    ("Katie!", "science"),
    ("Jphil", "science"),
    ("Erin", "connection"),
    ("Katie!", "meta"),
    ("Robert H", "connection"),
    ("Jacqueline Chang", "lore"),
    ("Jacqueline Chang", "connection"),
    ("Jacqueline Chang", "connection"),
    ("Hetvi", "lore"),
    ("Jacqueline Chang", "hype"),
    ("kushin", "lore"),
    ("kushin", "hype"),
    ("Chris Welker", "lore"),
    ("Jphil", "lore"),
    ("Tommy", "lore"),
    ("alexis ;)", "lore"),
    ("Katie!", "science"),
    ("Luke Chang", "meta"),
    ("Jphil", "meta"),
    ("Jphil", "meta"),
    ("Luke Chang", "meta"),
    ("Who dis", "meta"),
    ("Jphil", "meta"),
    ("Luke Chang", "meta"),
    ("Who dis", "meta"),
    ("Katie!", "meta"),
    ("Luke Chang", "meta"),
    ("kushin", "meta"),
    ("Luke Chang", "meta"),
    ("Who dis", "meta"),
    ("Jacqueline Chang", "lore"),
    ("Jphil", "meta"),
    ("Luke Chang", "meta"),
    ("kushin", "meta"),
    ("Katie!", "meta"),
    ("Luke Chang", "meta"),
    ("Luke Chang", "meta"),
    ("Jphil", "meta"),
    ("alexis ;)", "meta"),
    ("Yugantar", "meta"),
    ("Luke Chang", "meta"),
    ("Alana", "meta"),
    ("Alana", "meta"),
    ("Katie!", "science"),
    ("Alana", "science"),
    ("Jphil", "science"),
    ("sushpici0us", "science"),
    ("Dhaval", "science"),
    ("Nir", "science"),
    ("Hetvi", "meta"),
    ("Luke Chang", "meta"),
    ("sushpici0us", "meta"),
    ("Katie!", "meta"),
    ("Emma!", "meta"),
    ("shannon", "hype"),
    ("kushin", "meta"),
    ("kushin", "meta"),
    ("kushin", "meta"),
    ("alexis ;)", "science"),
    ("Jphil", "hype"),
    ("Robert H", "hype"),
    ("dae", "hype"),
    ("yuna!", "science"),
    ("dae", "hype"),
    ("alexis ;)", "science"),
    ("alexis ;)", "lore"),
    ("Jphil", "science"),
    ("Luke Chang", "science"),
    ("Helen", "lore"),
    ("alexis ;)", "science"),
    ("shannon", "science"),
    ("alexis ;)", "hype"),
    ("kushin", "connection"),
    ("yuna!", "meta"),
    ("Hetvi", "meta"),
    ("Luke Chang", "meta"),
    ("yuna!", "meta"),
    ("alexis ;)", "meta"),
    ("alexis ;)", "meta"),
    ("Luke Chang", "meta"),
    ("Katie!", "meta"),
    ("Yugantar", "meta"),
    ("sushpici0us", "connection"),
    ("Luke Chang", "meta"),
    ("Jphil", "meta"),
    ("Hetvi", "science"),
    ("Jacqueline Chang", "science"),
    ("Emma!", "meta"),
    ("Jacqueline Chang", "science"),
    ("alexis ;)", "hype"),
    ("Katie!", "meta"),
    ("Tommy", "science"),
    ("alexis ;)", "meta"),
    ("Clara", "science"),
    ("Katie!", "science"),
    ("Paxton", "science"),
    ("Clara", "greet"),
    ("alexis ;)", "science"),
    ("Luke Chang", "science"),
    ("Jphil", "science"),
    ("Grace < 3", "science"),
    ("alexis ;)", "hype"),
    ("Luke Chang", "science"),
    ("alexis ;)", "science"),
    ("kushin", "science"),
    ("alexis ;)", "science"),
    ("Katie!", "science"),
    ("Luke Chang", "science"),
    ("alexis ;)", "science"),
    ("alexis ;)", "hype"),
    ("Luke Chang", "science"),
    ("Jan", "hype"),
    ("Erik", "science"),
    ("Katie!", "meta"),
    ("alexis ;)", "science"),
    ("alexis ;)", "meta"),
    ("alexis ;)", "science"),
    ("alexis ;)", "science"),
    ("Paxton", "meta"),
    ("Emily Finn", "science"),
    ("alexis ;)", "meta"),
    ("Robert H", "meta"),
    ("alexis ;)", "meta"),
    ("theRealPaxton", "meta"),
    ("kushin", "hype"),
    ("Dominique", "tangent"),
    ("Robert H", "tangent"),
    ("Helen", "tangent"),
    ("alexis ;)", "tangent"),
    ("alexis ;)", "tangent"),
    ("Jphil", "tangent"),
    ("Paxton", "tangent"),
    ("alexis ;)", "tangent"),
    ("kushin", "tangent"),
    ("Luke Chang", "tangent"),
    ("Jacqueline Chang", "tangent"),
    ("kushin", "tangent"),
    ("Paxton", "tangent"),
    ("Who dis", "tangent"),
    ("Luke Chang", "tangent"),
    ("Jphil", "tangent"),
    ("Jacqueline Chang", "tangent"),
    ("Katie!", "tangent"),
    ("alexis ;)", "tangent"),
    ("Katie!", "science"),
    ("Dhaval", "science"),
    ("mimi", "science"),
    ("alexis ;)", "science"),
    ("alexis ;)", "meta"),
    ("Robert H", "science"),
    ("Hetvi", "science"),
    ("Gabriel R.", "congrats"),
    ("kushin", "connection"),
    ("theRealPaxton", "emoji"),
    ("alexis ;)", "lore"),
    ("theRealPaxton", "emoji"),
    ("theRealPaxton", "emoji"),
    ("kushin", "lore"),
    ("alexis ;)", "lore"),
    ("alexis ;)", "tangent"),
    ("kushin", "lore"),
    ("alexis ;)", "hype"),
    ("alexis ;)", "hype"),
    ("Neilly", "hype"),
    ("Neilly", "congrats"),
    ("alexis ;)", "meta"),
    ("alexis ;)", "meta"),
    ("Luke Chang", "congrats"),
    ("Dominique", "congrats"),
    ("Neilly", "congrats"),
    ("Helen", "congrats"),
    ("yuna!", "congrats"),
    ("matt", "congrats"),
    ("Amitai", "congrats"),
    ("Katie!", "congrats"),
    ("Tommy", "congrats"),
    ("Alexis :)", "congrats"),
    ("Alana", "congrats"),
    ("shannon", "congrats"),
    ("Tommy", "congrats"),
    ("Chris Welker", "congrats"),
    ("Hetvi", "congrats"),
    ("Shawn", "emoji"),
    ("Nir", "emoji"),
    ("Jphil", "congrats"),
    ("Yong", "congrats"),
    ("Dhaval", "emoji"),
    ("Helen", "congrats"),
    ("Shawn", "congrats"),
    ("Maisy", "congrats"),
    ("Dhaval", "emoji"),
    ("alexis ;)", "congrats"),
    ("James", "congrats"),
    ("Chelsea Mills", "congrats"),
    ("Chelsea Mills", "congrats"),
    ("Luke Chang", "thanks"),
    ("alexis ;)", "thanks"),
    ("Romy", "thanks"),
    ("alexis ;)", "thanks"),
    ("Luke Chang", "thanks"),
    ("Katie!", "thanks"),
    ("LT", "thanks"),
    ("LT", "thanks"),
    ("alexis ;)", "thanks"),
    ("kushin", "thanks"),
    ("alexis ;)", "emoji"),
    ("alexis ;)", "thanks"),
    ("Luke Chang", "thanks"),
    ("Jphil", "thanks"),
    ("yuna!", "thanks"),
    ("Katie!", "thanks"),
    ("Romy", "thanks"),
    ("Romy", "thanks"),
    ("Katie!", "thanks"),
    ("Luke Chang", "thanks"),
    ("alexis ;)", "meta"),
    ("Jphil", "thanks"),
    ("Luke Chang", "thanks"),
    ("Romy", "thanks"),
    ("yuna!", "thanks"),
    ("alexis ;)", "thanks"),
    ("alexis ;)", "thanks"),
    ("Luke Chang", "thanks"),
    ("alexis ;)", "thanks"),
    ("Katie!", "thanks"),
    ("Luke Chang", "thanks"),
    ("alexis ;)", "thanks"),
    ("Thalia", "emoji"),
    ("alexis ;)", "thanks"),
    ("Chris Welker", "thanks"),
    ("alexis ;)", "thanks"),
    ("Romy", "thanks"),
    ("Luke Chang", "thanks"),
    ("Erik", "thanks"),
    ("Robert H", "thanks"),
    ("alexis ;)", "thanks"),
    ("alexis ;)", "thanks"),
    ("alexis ;)", "thanks"),
    ("Katie!", "thanks"),
    ("Alana", "thanks"),
    ("alexis ;)", "thanks"),
    ("Yong", "congrats"),
    ("kushin", "congrats"),
    ("Arati", "emoji"),
    ("Alicia", "congrats"),
    ("Shawn", "congrats"),
    ("Hetvi", "congrats"),
    ("Robert H", "congrats"),
    ("Helen", "congrats"),
    ("Jphil", "congrats"),
    ("Jan", "congrats"),
    ("Emma!", "congrats"),
    ("Chris Welker", "congrats"),
    ("Jan", "meta"),
    ("Eshin", "emoji"),
]
